VtkFileWriter: VtkFileWriter::UnstructuredVtkWriter Class Reference
VtkFileWriter::UnstructuredVtkWriter Class Reference
#include <VtkFileWriter.h>
Public Member Functions
UnstructuredVtkWriter & setFile (std::filesystem::path &path)
Set the output file path where the VTK file will be written to. Will overwrite any path already set.
template<typename T >
UnstructuredVtkWriter & setPoints (const std::vector< VtkPoint< T > > &points)
Set the points of the VTK file. Will overwrite any points already set.
UnstructuredVtkWriter & setCells (std::vector< VtkCell > &&cells)
Set the cells of the VTK file. Will overwrite any cells already set.
UnstructuredVtkWriter & setCells (const std::vector< VtkCell > &cells)
Set the cells of the VTK file. Will overwrite any cells already set.
template<typename T >
UnstructuredVtkWriter & addPointData (const std::string &name, const std::vector< T > &pointData)
Add a point data set which will be written to the VTK file.
template<typename T , std::size_t N>
UnstructuredVtkWriter & addPointData (const std::string &name, const std::vector< std::array< T, N > > &pointData)
Add a point data set which will be written to the VTK file.
template<typename T >
UnstructuredVtkWriter & addCellData (const std::string &name, const std::vector< T > &cellData)
Add a cell data set which will be written to the VTK file.
template<typename T , std::size_t N>
UnstructuredVtkWriter & addCellData (const std::string &name, const std::vector< std::array< T, N > > &cellData)
Add a cell data set which will be written to the VTK file.
template<typename T >
UnstructuredVtkWriter & addFieldData (const std::string &name, const std::vector< T > &fieldData)
Add a field data set which will be written to the VTK file.
void write ()
void clear ()
Private Member Functions
template<typename T >
std::unique_ptr< internal::DataWrapper > createDataWrapper (const std::string &name, int numberOfComponents, const std::vector< T > &data)
Private Attributes
std::unique_ptr< std::filesystem::path > outputPath_
std::unique_ptr< internal::DataWrapper > points_
std::unique_ptr< std::vector< VtkCell > > cells_
std::vector< std::unique_ptr< internal::DataWrapper > > pointData_
std::vector< std::unique_ptr< internal::DataWrapper > > cellData_
std::vector< std::unique_ptr< internal::DataWrapper > > fieldData_
Detailed Description
Definition at line 235 of file VtkFileWriter.h.
Member Function Documentation
addCellData() [1/2]
template<typename T , std::size_t N> UnstructuredVtkWriter & VtkFileWriter::UnstructuredVtkWriter::addCellData (const std::string & name, const std::vector< std::array< T, N > > & cellData)
Add a cell data set which will be written to the VTK file.
Template Parameters
T
Parameters
name Name of the cell data set
addCellData
Returns
UnstructuredVtkWriter&
Definition at line 406 of file VtkFileWriter.h.
{
        std::vector<T> values;
        for (const std::array<T, N>& arr : cellData) {
            for (const T& v : arr) {
                values.push_back(v);
            }
        }
        cellData_.push_back(createDataWrapper(name, N, values));
        return *this;
    }
addCellData() [2/2]
template<typename T > UnstructuredVtkWriter & VtkFileWriter::UnstructuredVtkWriter::addCellData (const std::string & name, const std::vector< T > & cellData)
Add a cell data set which will be written to the VTK file.
Template Parameters
T
Parameters
name Name of the cell data set
addCellData
Returns
UnstructuredVtkWriter&
Definition at line 400 of file VtkFileWriter.h.
{
        cellData_.push_back(createDataWrapper(name, 1, cellData));
        return *this;
    }
addFieldData()
template<typename T > UnstructuredVtkWriter & VtkFileWriter::UnstructuredVtkWriter::addFieldData (const std::string & name, const std::vector< T > & fieldData)
Add a field data set which will be written to the VTK file.
Template Parameters
T
Parameters
name Name of the field data set
fieldData
Returns
UnstructuredVtkWriter&
Definition at line 419 of file VtkFileWriter.h.
{
        auto dataWrapper = createDataWrapper(name, 1, fieldData);
        fieldData_.push_back(std::move(dataWrapper));
        return *this;
    }
addPointData() [1/2]
template<typename T , std::size_t N> UnstructuredVtkWriter & VtkFileWriter::UnstructuredVtkWriter::addPointData (const std::string & name, const std::vector< std::array< T, N > > & pointData)
Add a point data set which will be written to the VTK file.
Template Parameters
T
Parameters
name Name of the point data set
pointData
Returns
UnstructuredVtkWriter&
Definition at line 386 of file VtkFileWriter.h.
{
        std::vector<T> values;
        for (const std::array<T, N>& arr : pointData) {
            for (const T& v : arr) {
                values.push_back(v);
            }
        }
       auto dataWrapper = createDataWrapper(name, N, values);
       pointData_.push_back(std::move(dataWrapper));
        return *this;
    }
addPointData() [2/2]
template<typename T > UnstructuredVtkWriter & VtkFileWriter::UnstructuredVtkWriter::addPointData (const std::string & name, const std::vector< T > & pointData)
Add a point data set which will be written to the VTK file.
Template Parameters
T
Parameters
name Name of the point data set
pointData
Returns
UnstructuredVtkWriter&
Definition at line 379 of file VtkFileWriter.h.
{
        auto dataWrapper = createDataWrapper(name, 1, pointData);
        pointData_.push_back(std::move(dataWrapper));
        return *this;
    }
Referenced by main().
clear()
void VtkFileWriter::UnstructuredVtkWriter::clear () inline
Definition at line 444 of file VtkFileWriter.h.
{
        outputPath_.reset();
        points_.reset();
        cells_.reset();
        pointData_.clear();
        cellData_.clear();
    }
createDataWrapper()
template<typename T > std::unique_ptr< internal::DataWrapper > VtkFileWriter::UnstructuredVtkWriter::createDataWrapper (const std::string & name, int numberOfComponents, const std::vector< T > & data) private
Definition at line 453 of file VtkFileWriter.h.
{
        std::unique_ptr<internal::DataWrapper> dataWrapper = std::unique_ptr<internal::DataWrapper>(new internal::DataWrapperImpl<T>());
        internal::DataWrapperImpl<T>& dataWrapperImpl = *static_cast<internal::DataWrapperImpl<T>*>(dataWrapper.get());
        dataWrapperImpl.name = name;
        dataWrapperImpl.numberOfComponents = numberOfComponents;
        dataWrapperImpl.totalDataPoints = data.size();
        dataWrapperImpl.dataType = internal::getVtkDataType<T>();
        dataWrapperImpl.values = data;
        return std::move(dataWrapper);
    }
Referenced by addCellData(), addCellData(), addFieldData(), addPointData(), addPointData(), and setPoints().
setCells() [1/2]
UnstructuredVtkWriter & VtkFileWriter::UnstructuredVtkWriter::setCells (const std::vector< VtkCell > & cells)
Set the cells of the VTK file. Will overwrite any cells already set.
Parameters
cells
Returns
UnstructuredVtkWriter&
Definition at line 373 of file VtkFileWriter.h.
{
        cells_ = std::make_unique<std::vector<VtkCell>>(cells);
        return *this;
    }
setCells() [2/2]
UnstructuredVtkWriter & VtkFileWriter::UnstructuredVtkWriter::setCells (std::vector< VtkCell > && cells)
Set the cells of the VTK file. Will overwrite any cells already set.
Parameters
cells
Returns
UnstructuredVtkWriter&
Definition at line 368 of file VtkFileWriter.h.
{
        cells_ = std::make_unique<std::vector<VtkCell>>(std::move(cells));
        return *this;
    }
Referenced by main().
setFile()
UnstructuredVtkWriter & VtkFileWriter::UnstructuredVtkWriter::setFile (std::filesystem::path & path)
Set the output file path where the VTK file will be written to. Will overwrite any path already set.
Parameters
path
Returns
UnstructuredVtkWriter&
Definition at line 347 of file VtkFileWriter.h.
{
        outputPath_ = std::make_unique<std::filesystem::path>(std::forward<std::filesystem::path>(path));
        return *this;
    }
Referenced by main().
setPoints()
template<typename T > UnstructuredVtkWriter & VtkFileWriter::UnstructuredVtkWriter::setPoints (const std::vector< VtkPoint< T > > & points)
Set the points of the VTK file. Will overwrite any points already set.
Template Parameters
T
Parameters
points
Returns
UnstructuredVtkWriter&
Definition at line 354 of file VtkFileWriter.h.
{
        std::vector<T> values;
        values.reserve(points.size());
        for (const VtkPoint<T>& point : points) {
            values.push_back(point.x);
            values.push_back(point.y);
            values.push_back(point.z);
        }
        points_ = createDataWrapper("Points", 3, values);
        return *this;
    }
Referenced by main().
write()
void VtkFileWriter::UnstructuredVtkWriter::write ()
Definition at line 425 of file VtkFileWriter.h.
{
        internal ::UnstructuredVtkXmlWriter xmlWriter{};
        std::vector<internal::DataWrapper*> pointData;
        std::vector<internal::DataWrapper*> cellData;
        std::vector<internal::DataWrapper*> fieldData;
        for (const auto& p : pointData_) {
            pointData.push_back(p.get());
        }
        for (const auto& c : cellData_) {
            cellData.push_back(c.get());
        }
        for (const auto& f : fieldData_) {
            fieldData.push_back(f.get());
        }
        xmlWriter.writeToXml(*outputPath_, *points_, *cells_, pointData, cellData, fieldData);
    }
Referenced by main().
Member Data Documentation
cellData_
std::vector<std::unique_ptr<internal::DataWrapper> > VtkFileWriter::UnstructuredVtkWriter::cellData_ private
Definition at line 343 of file VtkFileWriter.h.
Referenced by addCellData(), addCellData(), clear(), and write().
cells_
std::unique_ptr<std::vector<VtkCell> > VtkFileWriter::UnstructuredVtkWriter::cells_ private
Definition at line 340 of file VtkFileWriter.h.
Referenced by clear(), setCells(), setCells(), and write().
fieldData_
std::vector<std::unique_ptr<internal::DataWrapper> > VtkFileWriter::UnstructuredVtkWriter::fieldData_ private
Definition at line 344 of file VtkFileWriter.h.
Referenced by addFieldData(), and write().
outputPath_
std::unique_ptr<std::filesystem::path> VtkFileWriter::UnstructuredVtkWriter::outputPath_ private
Definition at line 338 of file VtkFileWriter.h.
Referenced by clear(), setFile(), and write().
pointData_
std::vector<std::unique_ptr<internal::DataWrapper> > VtkFileWriter::UnstructuredVtkWriter::pointData_ private
Definition at line 342 of file VtkFileWriter.h.
Referenced by addPointData(), addPointData(), clear(), and write().
points_
std::unique_ptr<internal::DataWrapper> VtkFileWriter::UnstructuredVtkWriter::points_ private
Definition at line 339 of file VtkFileWriter.h.
Referenced by clear(), setPoints(), and write().
The documentation for this class was generated from the following file:
include/VtkFileWriter/VtkFileWriter.h